
language: node_js
sudo: required
services:
  - docker
node_js:
  - "4"
  - "5"
  - "6"
before_install:
  - "cp test/properties.docker.coffee test/properties.coffee"
  - "docker run --name stargate -d -p 60080:8080 sixeyed/hbase-stargate"
