
language: node_js
sudo: required
services:
  - docker
node_js:
  - "4"
  - "5"
  - "6"
before_install:
  - "docker build -t hbase-rest hbase-rest-reverse-proxy/"
  - "docker run -d -p 60080:8100 hbase-rest"
script:
  - cp test/properties.docker.coffee test/properties.coffee && npm test
  - cp test/properties_with_path.docker.coffee test/properties.coffee && npm test